Отображение диалога
likvidator3301/vincent pull request #7
Opened 2021-05-03 13:20 UTC by sadovnichek

**Abstract**
Я не знаю, передаются ли настройки Unity через гит, но даже если нет: то вот что я сделал: я поменял у Canvas - Render Mode на Screen Space (Camera) - тогда камера будет отображать Canvas правильно.

**What I did**
Получаем текущий узел диалога и отправляем его в NewTextEventRepository. Далее, в DisplayTextService Update-ом просматриваем содержимое узла. Если он завершающий - удаляем все кнопки и дезактивируем ScrollRect. В противном случае идём в ShowDialogueState и выводим реплику NPC как текст и варианты ответа как кнопки.

**Problems**
Я заметил, что при клике на произвольный тег, он обрабатывается 2 раза подряд (это можно понять, если вставить Debug.Log в MouseHelper. Кажется, что для простых предметов это некритично, но для кнопок это вызывает следующее: мы как бы кликаем два раза подряд в одну и ту же область, тем самым проскакивая некоторые реплики с ответами. С этим надо что-то сделать. Я не думаю, что это слишком сложно, можно сохранять предыдущую точку нажатия и сравнивать её с текущей - и если они совпали - то игнорировать.

2021-05-03 13:51 UTC, likvidator3301 requested changes

2021-05-03 13:51 UTC, likvidator3301 commented on Assets/Scripts/Common/Constants.cs
> +            public const string Button = "Button";
Может DialogueButton?

А то у нас скорее всего еще много кнопок появится, их бы различать как-то

2021-05-03 13:51 UTC, likvidator3301 commented on Assets/Scripts/Common/GameController.cs
> +            if (textPanel == null)
Здесь такого быть не может, потому что ты .First() используешь

Если коллекция будет пустая, то кинется исключение

Тут либо использовать .FirstOrDefault(), либо вручную проверять длину коллекции

2021-05-03 13:51 UTC, likvidator3301 commented on Assets/Scripts/Common/GameController.cs
> +                return;
Здесь надо не return, а GameInitializationException кинуть

Потому что это критичный контроллер, его не может не быть

2021-05-03 13:51 UTC, likvidator3301 commented on Assets/Scripts/Common/Helpers/MouseHelper.cs
> +                    Debug.Log(hitInfo.collider.gameObject.tag);
В мастере этому точно не место)

2021-05-03 13:51 UTC, likvidator3301 commented on Assets/Scripts/Markers/ButtonMarker.cs
> +            return Instantiate(this, GameObject.Find("Canvas").transform);
хмммм, некрасиво

во-первых, маркеры задумывались как просто маркеры+небольшая конфигурация

вся логика должна быть в сервисах

во-вторых, тут появляется неявная слабая зависимость от Canvas'a

Надо подумать, как сделать красиво

2021-05-03 13:51 UTC, likvidator3301 commented on Assets/Scripts/Npc/Dialogues/DisplayDialogueService.cs
> +        public static void ShowText(DialogueNode node)
Зачем public static?

2021-05-03 13:51 UTC, likvidator3301 commented on Assets/Scripts/Npc/NpcController.cs
> +            var displayDialogueService = new DisplayDialogueService(dialogueRepository, newTextEventRepository);
метод называется CreateStartDialogueService 
а создается тут 2 сервиса

лучше всего разнести их создание в 2 разных

2021-05-03 13:51 UTC, likvidator3301 commented on Assets/Scripts/Markers/ButtonMarker.cs
> +        public Text buttonText;
Все публичное с большой буквы)

2021-05-04 06:44 UTC, likvidator3301 requested changes

2021-05-04 06:44 UTC, likvidator3301 commented on Assets/Scripts/Npc/Dialogues/DisplayDialogueService.cs
> +                Debug.Log("Answer: " + answer.Key);
Ну и debug.log тоже надо выпилить, перед тем как в мастер лить

2021-05-04 06:44 UTC, likvidator3301 commented on Assets/Scripts/Npc/NpcController.cs
> +using UnityEngine.UI;
зачем?

2021-05-04 06:44 UTC, likvidator3301 commented on Assets/Scripts/TextPanel/DisplayTextService.cs
> +        public void DestroyButtons(List<ButtonMarker> buttons)
private

2021-05-04 06:44 UTC, likvidator3301 commented on Assets/Scripts/TextPanel/DisplayTextService.cs
> +        public void ShowDialogueState(DialogueNode node)
private

2021-05-04 06:44 UTC, likvidator3301 commented on Assets/Scripts/TextPanel/DisplayTextService.cs
> +        private const int scrollRectWidth = 818;
константы с большой буквы

2021-05-04 06:44 UTC, likvidator3301 commented on Assets/Scripts/TextPanel/DisplayTextService.cs
> +        private const int scrollRectWidth = 818;
И еще бы константу отступом от остальных полей отделить

2021-05-04 06:44 UTC, likvidator3301 commented on Assets/Scripts/TextPanel/DisplayTextService.cs
> +            int posX = -280;
var?

2021-05-04 06:44 UTC, likvidator3301 commented on Assets/Scripts/TextPanel/DisplayTextService.cs
> +            var endButton = button.Instantiate();
может finishButton?

2021-05-04 06:44 UTC, likvidator3301 commented on Assets/Scripts/TextPanel/Repositories/NewTextEvent.cs
> +            this.node = node;
тут бы на null проверить по-хорошему

2021-05-04 07:09 UTC, likvidator3301 commented
Еще  хочется все классы сделать публичными, для однообразия

2021-05-05 11:13 UTC, likvidator3301 requested changes

2021-05-05 11:13 UTC, likvidator3301 commented on Assets/Scripts/Common/GameController.cs
> +            var scrollRect = (FindObjectsOfType(typeof(ScrollRect)) as ScrollRect[]).First();
Давай здесь тоже FirstOrDefault() заиспользуем, и будем проверять на null?

Если мы так сделаем, то у нас будет понятное нам GameInitializationException

А если оставить так, то упадет с непонятным InvalidOpetationException


Когда у нас будет >1 сцены, это поможет нам быстрее ловить возникающие баги

2021-05-05 11:13 UTC, likvidator3301 commented on Assets/Scripts/Common/Helpers/MouseHelper.cs
> +                {
зочем?

2021-05-05 11:13 UTC, likvidator3301 commented on Assets/Scripts/Common/Helpers/MouseHelper.cs
> -
зочем

2021-05-05 11:13 UTC, likvidator3301 commented on Assets/Scripts/Markers/ButtonMarker.cs
> +            return Instantiate(this, GameObject.Find("Canvas").transform);
пока вольем так тогда, но потом надо обязательно поменять

2021-05-05 11:13 UTC, likvidator3301 commented on Assets/Scripts/Npc/Dialogues/DisplayDialogueService.cs
> +        public static void ShowText(DialogueNode node)
Актуально

2021-05-05 11:13 UTC, likvidator3301 commented on Assets/Scripts/Npc/Dialogues/DisplayDialogueService.cs
> +                Debug.Log("Answer: " + answer.Key);
Актуально

2021-05-05 11:13 UTC, likvidator3301 commented on Assets/Scripts/Npc/Dialogues/DisplayDialogueService.cs
> +            //ShowText(dialogue.Value);
Комментарии в мастере, мее

2021-05-05 11:13 UTC, likvidator3301 commented on Assets/Scripts/TextPanel/DisplayTextService.cs
> +            if (currentNode.Text != "end")
У, очень нестабильно

Во-первых, прямо в коде захардкожен текст, который внезапно должен быть в тексте с точностью даже до пробелов и регистра

Во-вторых, вообще решение очень спорное
Кажется, это должна быть отдельная кнопка, с отдельным сервисом, который это всё обрабатывает

Этот сервис занимается сменой узла диалога, второй занимается управлением самим диалогом

2021-05-05 11:13 UTC, likvidator3301 commented on ProjectSettings/UnityConnectSettings.asset
> +  m_Enabled: 1
Зачем нам юнити.коннект?

2021-05-05 11:13 UTC, likvidator3301 commented on Assets/Scripts/TextPanel/DisplayTextService.cs
> +namespace Assets.Scripts.TextPanel
Мне вообще кажется этот сервис перегруженным по логике

Он по сути занимается аж тремя вещами

1. Он рисует кнопки 
2. Отображает скроллРект
3. Занимается окончанием диалога

2021-05-05 14:03 UTC, sadovnichek commented on ProjectSettings/UnityConnectSettings.asset
> +  m_Enabled: 1
Я не знаю, а что это вообще такое?

2021-05-07 18:17 UTC, sadovnichek commented on Assets/Scripts/TextPanel/DisplayTextService.cs
> +            if (currentNode.Text != "end")
По первому я не совсем понял, поконкретнее, плз

2021-05-07 18:18 UTC, merged